# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()


# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x1

array([5, 0, 2, 0, 8, 0])

In [4]:
x2

array([[4, 5, 8, 5],
       [3, 2, 4, 1],
       [8, 7, 9, 3]])

In [5]:
x3

array([[[5, 7, 4, 5, 9],
        [6, 3, 7, 4, 6],
        [6, 4, 7, 5, 5],
        [8, 9, 0, 0, 2]],

       [[7, 9, 7, 5, 9],
        [5, 6, 9, 0, 4],
        [4, 3, 7, 6, 5],
        [0, 6, 1, 2, 1]],

       [[0, 9, 4, 5, 1],
        [7, 8, 8, 1, 1],
        [6, 4, 2, 4, 6],
        [5, 1, 0, 6, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [7]:
# Attributes of 2-dimensional array
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [8]:
# Attributes of 3-dimensional array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(x1)
df

0
0  5
1  0
2  2
3  0
4  8
5  0

In [10]:
# Create an array of shape (10, 2) with only ones
a1 = np.ones((10,2), dtype=np.int32)
a1
print("a1 shape:", a1.shape)

a1 shape: (10, 2)


In [11]:
# Create an array of shape (7, 2, 3) of only zeros
a2 = np.zeros((7,2,3), dtype=np.int32)
a2
# print("a2 shape:", a2.shape)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [12]:
# Create an array within a range of 0 and 100 with step 3
a3 = np.arange(0,100,3)
a3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a4 = np.random.randint(0,10, size=(7,2))
a4
# print(a4.size)
print("x3 ndim: ", a4.ndim)
print("x3 shape:", a4.shape)
print("x3 size: ", a4.size)

x3 ndim:  2
x3 shape: (7, 2)
x3 size:  14


In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a5 = np.random.random((3,5))
a5

array([[0.87625795, 0.60234505, 0.9370398 , 0.11758517, 0.86516607],
       [0.39632341, 0.27897202, 0.71432   , 0.98397689, 0.86305314],
       [0.59693685, 0.05347862, 0.12146944, 0.09566069, 0.77008366]])

In [15]:

print("ndim: ", a5.ndim)
print("shape:", a5.shape)
print("size: ", a5.size)

ndim:  2
shape: (3, 5)
size:  15


In [20]:
# Set the random seed to 42
np.random.seed(42)  # seed for reproducibility

x1 = np.random.randint(0,10, size=(4,6))  # One-dimensional array
x1
# Create a random array of numbers between 0 & 10 of size (4, 6)
# x1.shape

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [31]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(1)  # seed for reproducibility
x1 = np.random.randint(0,10, size=(3,7))  # One-dimensional array
x1

# Find the unique numbers in the array you just created


array([[5, 8, 9, 5, 0, 0, 1],
       [7, 6, 9, 2, 4, 5, 2],
       [4, 2, 4, 7, 7, 9, 1]])

In [32]:
np.unique(x1)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [34]:
# Find the 0'th index of the latest array you created
x1[0]

array([5, 8, 9, 5, 0, 0, 1])

In [50]:
# Get the first 2 rows of latest array you created
x1[:2,:6]

array([[5, 8, 9, 5, 0, 0],
       [7, 6, 9, 2, 4, 5]])

In [51]:
# Get the first 2 values of the first 2 rows of the latest array
x1[:2,:2]

array([[5, 8],
       [7, 6]])

In [56]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(1)  # seed for reproducibility
x1 = np.random.randint(0,10, size=(3,5))  # One-dimensional array
x2 = np.ones((3,5),np.int8)
x1


array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4]])

In [57]:
x2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [58]:
# Add the two arrays together
x3 = x1 + x2
x3

array([[ 6,  9, 10,  6,  1],
       [ 1,  2,  8,  7, 10],
       [ 3,  5,  6,  3,  5]])

In [64]:
# Create another array of ones of shape (5, 3)
x4 = np.ones((5,3),np.int8)

In [65]:
# Try add the array of ones and the other most recent array together
x5 = x3 + x4.reshape(3,5)
x5

array([[ 7, 10, 11,  7,  2],
       [ 2,  3,  9,  8, 11],
       [ 4,  6,  7,  4,  6]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
x4 = np.ones((3,5),np.int8)

In [68]:
# Subtract the new array of ones from the other most recent array
x6 = x5 - x4.reshape(3,5)
x6

array([[ 6,  9, 10,  6,  1],
       [ 1,  2,  8,  7, 10],
       [ 3,  5,  6,  3,  5]])

In [70]:
# Multiply the ones array with the latest array
x7 = x4*x6.T
x7

array([[ 6,  1,  3],
       [ 9,  2,  5],
       [10,  8,  6],
       [ 6,  7,  3],
       [ 1, 10,  5]])

In [71]:
# Take the latest array to the power of 2 using '**'
x8 =x7**2
x8

array([[ 36,   1,   9],
       [ 81,   4,  25],
       [100,  64,  36],
       [ 36,  49,   9],
       [  1, 100,  25]])

In [72]:
# Do the same thing with np.square()
x9 = np.square(x8)
x9

array([[ 1296,     1,    81],
       [ 6561,    16,   625],
       [10000,  4096,  1296],
       [ 1296,  2401,    81],
       [    1, 10000,   625]])

In [73]:
# Find the mean of the latest array using np.mean()
x9.mean()

2558.4

In [74]:
# Find the maximum of the latest array using np.max()
x9.max()

10000

In [75]:
# Find the minimum of the latest array using np.min()
x9.min()

1

In [76]:
# Find the standard deviation of the latest array
x9.std()

3398.4413839288154

In [78]:
# Find the variance of the latest array
x9.var()

11549403.840000002

In [79]:
# Reshape the latest array to (3, 5, 1)
x9.reshape(3,5,1)

array([[[ 1296],
        [    1],
        [   81],
        [ 6561],
        [   16]],

       [[  625],
        [10000],
        [ 4096],
        [ 1296],
        [ 1296]],

       [[ 2401],
        [   81],
        [    1],
        [10000],
        [  625]]])

In [80]:
# Transpose the latest array
x9.T

array([[ 1296,  6561, 10000,  1296,     1],
       [    1,    16,  4096,  2401, 10000],
       [   81,   625,  1296,    81,   625]])

What does the transpose do?

In [83]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(1)  # seed for reproducibility
x1 = np.random.randint(0,10, size=(3,3))  # One-dimensional array
x2 = np.random.randint(0,10, size=(3,2))  # One-dimensional array
x1, x2

(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6]]),
 array([[9, 2],
        [4, 5],
        [2, 4]]))

In [82]:
# Perform a dot product on the two newest arrays you created
x3 = x1.dot(x2)
x3

array([[95, 86],
       [45, 10],
       [49, 61]])

In [85]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(1)  # seed for reproducibility
x1 = np.random.randint(0,10, size=(4,3))  # One-dimensional array
x2 = np.random.randint(0,10, size=(4,3))  # One-dimensional array
x1, x2

(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]]),
 array([[5, 2, 4],
        [2, 4, 7],
        [7, 9, 1],
        [7, 0, 6]]))

In [87]:
# Perform a dot product on the two newest arrays you created
x3 = x1.dot(x2.T)
x3

array([[ 77, 105, 116,  89],
       [ 25,  10,  35,  35],
       [ 43,  72,  76,  43],
       [ 65,  54,  85,  87]])

It doesn't work. How would you fix it?

In [88]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
x3 = x1.dot(x2.T)
x3

array([[ 77, 105, 116,  89],
       [ 25,  10,  35,  35],
       [ 43,  72,  76,  43],
       [ 65,  54,  85,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [134]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(5)  # seed for reproducibility
x1 = np.random.randint(0,10, size=(3,3))  # One-dimensional array
x2 = np.random.randint(0,10, size=(3,3))  # One-dimensional array
x1, x2

(array([[3, 6, 6],
        [0, 9, 8],
        [4, 7, 0]]),
 array([[0, 7, 1],
        [5, 7, 0],
        [1, 4, 6]]))

In [90]:
# Compare the two arrays with '>'
x1 > x2

array([[False,  True,  True],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [91]:
# Compare the two arrays with '>='
x1 >= x2

array([[False,  True,  True],
       [ True, False, False],
       [False,  True, False]])

In [92]:
# Find which elements of the first array are greater than 7
x3 = x1 > 7
x3

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [95]:
# Which parts of each array are equal? (try using '==')
x4 = x1 == x2
x4

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [135]:
x5 = x1
x5

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0]])

In [136]:
# Sort one of the arrays you just created in ascending order
np.sort(x1)

array([[3, 6, 6],
       [0, 8, 9],
       [0, 4, 7]])

In [137]:
x5

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0]])

In [138]:
# Sort the indexes of one of the arrays you just created
np.argsort(x5)

array([[0, 1, 2],
       [0, 2, 1],
       [2, 0, 1]])

In [172]:
x5

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0]])

In [165]:
x8 = np.argmax(x5)

In [166]:
# Find the index with the maximum value in one of the arrays you've created
x8 = np.argmax(x5)
x8

4

In [167]:
# Find the index with the minimum value in one of the arrays you've created
x9 = np.argmin(x5)
x9

3

In [168]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
x18 = np.argmax(x5, axis=1)
x18

array([1, 1, 1])

In [171]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
x19 = np.argmin(x5, axis=0)
x19

array([1, 0, 2])

In [113]:
# Create an array of normally distributed random numbers
x1 = np.random.normal(loc=0, scale=1, size=10)
x1

array([ 0.17133845, -0.44285144,  1.70490377,  0.92434585, -1.30486124,
       -0.38057504, -0.74362701, -0.43712177, -0.42645009,  1.3814073 ])

In [111]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a5 = np.linspace(1,100,10,dtype=int)
a5

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.