# A Simple Scikit-Learn Classification Workflow

This notebook shows a breif workflow you might use with `scikit-learn` to build a machine learning model to classify whether or not a patient has heart disease.

It follows the diagram below:

<img src="https://github.com/OCR-tech/zero-to-mastery-ml/blob/master/images/sklearn-workflow.png?raw=1"/>

**Note:** This workflow assumes your data is ready to be used with machine learning models (is numerical, has no missing values).

In [1]:
# Standard imports
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## 1. Get the data ready

In [3]:
# Import dataset
# heart_disease = pd.read_csv("../data/heart-disease.csv")
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv")

# View the data
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

With this example, we're going to use all of the columns except the target column to predict the targert column.

In other words, using a patient's medical and demographic data to predict whether or not they have heart disease.

In [4]:
# Create X (all the feature columns)
X = heart_disease.drop("target", axis=1)

# Create y (the target column)
y = heart_disease["target"]

In [5]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

# View the data shapes
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

## 2. Choose the model/estimator

You can do this using the [Scikit-Learn machine learning map](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html).

<img src="https://github.com/OCR-tech/zero-to-mastery-ml/blob/master/images/sklearn-ml-map.png?raw=1" width=500/>

In Scikit-Learn, machine learning models are referred to as estimators.

In this case, since we're working on a classification problem, we've chosen the RandomForestClassifier estimator which is part of the ensembles module.

In [6]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

## 3. Fit the model to the data and use it to make a prediction

A model will (attempt to) learn the patterns in a dataset by calling the `fit()` function on it and passing it the data.

In [15]:
model.fit(X_train, y_train)

RandomForestClassifier()

Once a model has learned patterns in data, you can use them to make a prediction with the `predict()` function.

In [12]:
# Make predictions
y_preds = model.predict(X_test)

In [13]:
# This will be in the same format as y_test
y_preds

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1])

In [18]:
X_test, type(X_test), X_test.shape

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
 173   58    1   2       132   224    0        0      173      0      3.2   
 178   43    1   0       120   177    0        0      120      1      2.5   
 210   57    1   2       128   229    0        0      150      0      0.4   
 236   58    1   0       125   300    0        0      171      0      0.0   
 252   62    0   0       138   294    1        1      106      0      1.9   
 ..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
 5     57    1   0       140   192    0        1      148      0      0.4   
 298   57    0   0       140   241    0        1      123      1      0.2   
 144   76    0   2       140   197    0        2      116      0      1.1   
 76    51    1   2       125   245    1        0      166      0      2.4   
 30    41    0   1       105   198    0        1      168      0      0.0   
 
      slope  ca  thal  
 173      2   2     3  
 178      1   0     3  
 2

In [17]:
X_test.loc[206]

KeyError: 26

In [ ]:
heart_disease.loc[206]

age          59.0
sex           1.0
cp            0.0
trestbps    110.0
chol        239.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
target        0.0
Name: 206, dtype: float64

In [ ]:
# Make a prediction on a single sample (has to be array)
model.predict(np.array(X_test.loc[206]).reshape(1, -1))

array([0])

## 4. Evaluate the model
A trained model/estimator can be evaluated by calling the `score()` function and passing it a collection of data.

In [ ]:
# On the training set
model.score(X_train, y_train)

0.9911894273127754

In [ ]:
# On the test set (unseen)
model.score(X_test, y_test)

0.75

## 5. Experiment to improve (hyperparameter tuning)

A model's first evaluation metrics aren't always its last. One way to improve a models predictions is with hyperparameter tuning.

In [ ]:
# Try different numbers of estimators (n_estimators is a hyperparameter you can change)
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.7236842105263158

Trying model with 20 estimators...
Model accruacy on test set: 0.7368421052631579

Trying model with 30 estimators...
Model accruacy on test set: 0.7368421052631579

Trying model with 40 estimators...
Model accruacy on test set: 0.7368421052631579

Trying model with 50 estimators...
Model accruacy on test set: 0.6973684210526315

Trying model with 60 estimators...
Model accruacy on test set: 0.7631578947368421

Trying model with 70 estimators...
Model accruacy on test set: 0.7631578947368421

Trying model with 80 estimators...
Model accruacy on test set: 0.7631578947368421

Trying model with 90 estimators...
Model accruacy on test set: 0.75



**Note:** It's best practice to test different hyperparameters with a validation set or cross-validation.

In [ ]:
from sklearn.model_selection import cross_val_score

# Try different numbers of estimators with cross-validation and no cross-validation
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5)) * 100}%")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.7236842105263158
Cross-validation score: 78.53551912568305%

Trying model with 20 estimators...
Model accruacy on test set: 0.75
Cross-validation score: 79.84699453551912%

Trying model with 30 estimators...
Model accruacy on test set: 0.7763157894736842
Cross-validation score: 80.50819672131148%

Trying model with 40 estimators...
Model accruacy on test set: 0.7631578947368421
Cross-validation score: 82.15300546448088%

Trying model with 50 estimators...
Model accruacy on test set: 0.7368421052631579
Cross-validation score: 81.1639344262295%

Trying model with 60 estimators...
Model accruacy on test set: 0.7631578947368421
Cross-validation score: 83.47540983606557%

Trying model with 70 estimators...
Model accruacy on test set: 0.7236842105263158
Cross-validation score: 81.83060109289617%

Trying model with 80 estimators...
Model accruacy on test set: 0.7631578947368421
Cross-validation score: 82.81420765027322%

Trying 

## 6. Save a model for later use

A trained model can be exported and saved so it can be imported and used later. One way to save a model is using Python's `pickle` module.

In [ ]:
import pickle

# Save trained model to file
pickle.dump(model, open("random_forest_model_1.pkl", "wb"))

In [ ]:
# Load a saved model and make a prediction on a single example
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.predict(np.array(X_test.loc[206]).reshape(1, -1))

array([0])